Class {
	#name : #GtApLexiconCustom,
	#superclass : #GtApLexiconEntity,
	#instVars : [
		'description',
		'id'
	],
	#category : #'Gt4AtProto-Lexicon'
}

{ #category : #accessing }
GtApLexiconCustom >> description [
	^ description
]

{ #category : #accessing }
GtApLexiconCustom >> description: anObject [
	description := anObject
]

{ #category : #accessing }
GtApLexiconCustom >> id [
	^ id
]

{ #category : #accessing }
GtApLexiconCustom >> id: anObject [
	id := anObject
]
