Class {
	#name : #GtApLexiconPrimitive,
	#superclass : #GtApLexiconDefinition,
	#instVars : [
		'description',
		'id'
	],
	#category : #'Gt4AtProto-Lexicon-Definitions'
}

{ #category : #accessing }
GtApLexiconPrimitive >> description [
	^ description
]

{ #category : #accessing }
GtApLexiconPrimitive >> description: anObject [
	description := anObject
]

{ #category : #accessing }
GtApLexiconPrimitive >> id [
	^ id
]

{ #category : #accessing }
GtApLexiconPrimitive >> id: anObject [
	id := anObject
]
