Class {
	#name : #GtApLexiconVideo,
	#superclass : #GtApLexiconData,
	#instVars : [
		'maxWidth',
		'maxHeight',
		'maxLength'
	],
	#category : #'Gt4AtProto-Lexicon'
}

{ #category : #accessing }
GtApLexiconVideo >> maxHeight [
	^ maxHeight
]

{ #category : #accessing }
GtApLexiconVideo >> maxHeight: anObject [
	maxHeight := anObject
]

{ #category : #accessing }
GtApLexiconVideo >> maxLength [
	^ maxLength
]

{ #category : #accessing }
GtApLexiconVideo >> maxLength: anObject [
	maxLength := anObject
]

{ #category : #accessing }
GtApLexiconVideo >> maxWidth [
	^ maxWidth
]

{ #category : #accessing }
GtApLexiconVideo >> maxWidth: anObject [
	maxWidth := anObject
]
